import Options
from os import unlink, symlink, popen
from os.path import exists

srcdir = "."
blddir = "build"
VERSION = "0.0.1"

def set_options(opt):
	opt.tool_options("compiler_cxx")

def configure(conf):
	conf.check_tool("compiler_cxx")
	conf.check_tool("node_addon")
	conf.env.append_value('CFLAGS', ['-I ../include/'])

def build(bld):
	obj = bld.new_task_gen('cxx', 'shlib', 'node_addon')
	obj.target = 'uatraits'
	obj.source = ['uatraits.cpp', 'dict_wrapper.cpp']
	obj.includes = ['../include/', '/usr/include/libxml2', '../config/']
	obj.libpath = ['../../library/.libs']
	obj.libs = ['uatraits']

def shutdown():
	if Options.commands['clean']:
		if exists('uatraits.node'): unlink('uatraits.node')
	else:
		if exists('build/Release/uatraits.node') and not exists('uatraits.node'):
			symlink('build/Release/uatraits.node', 'uatraits.node')
		if exists('build/default/uatraits.node') and not exists('uatraits.node'):
			symlink('build/default/uatraits.node', 'uatraits.node')

